//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crawler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crawler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classifer.
        /// </summary>
        internal static string frmClassifier_cmdAdd_Click_Classifer {
            get {
                return ResourceManager.GetString("frmClassifier_cmdAdd_Click_Classifer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Added.
        /// </summary>
        internal static string frmClassifier_cmdAdd_Click_Rule_Added {
            get {
                return ResourceManager.GetString("frmClassifier_cmdAdd_Click_Rule_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARFF generated!.
        /// </summary>
        internal static string frmCrawler_cmdArff_Click_ARFF_generated_ {
            get {
                return ResourceManager.GetString("frmCrawler_cmdArff_Click_ARFF_generated_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \storage\.
        /// </summary>
        internal static string frmCrawler_ReCreateSetting__storage_ {
            get {
                return ResourceManager.GetString("frmCrawler_ReCreateSetting__storage_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal parameter!.
        /// </summary>
        internal static string Program_Main_Illegal_parameter_ {
            get {
                return ResourceManager.GetString("Program_Main_Illegal_parameter_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Spider_robot_with_shadow {
            get {
                object obj = ResourceManager.GetObject("Spider_robot_with_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
